sudo: required
language: php

php:
  - '7.0'

services:
  - docker

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite
  APP_KEY: 16efa6c23c2e8c705826b0e66778fbe7

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install --no-progress --no-spin
  - gulp
  - cp .env.example .env
  - php artisan migrate
script: ./runtests