sudo: required
language: php

php:
  - '7.0'

services:
  - docker

env:
  - TRAVIS_NODE_VERSION="6"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - composer install --prefer-dist
  - npm install --no-progress --no-spin
  - gulp
  - cp .env.example .env
script: ./runtests