language: php

php:
  - '7.0'

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: sqlite
  DB_DATABASE: database/db.sqlite

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install --no-progress --no-spin &>/dev/null
  - gulp &>/dev/null
  - cp .env.example .env
  - composer install --no-interaction &>/dev/null
  - php artisan key:generate
  - touch database/db.sqlite
  - php artisan migrate
script: ./runtests --debug