#!/usr/bin/env python

import os, time, sys
import signal
from functools import partial
from subprocess import Popen, check_call

proc_run = partial(Popen, shell=True, preexec_fn=os.setsid)

def stop_process(process):
    os.killpg(os.getpgid(process.pid), signal.SIGKILL)

def main():
    web_log = open('tests/_output/webserver.log', "w")
    web = proc_run('php artisan serve', stdout=web_log, stderr=web_log)
    phantomjs_log = open('tests/_output/phantomjs.log', "w")
    phantomjs = proc_run('node_modules/.bin/phantomjs --webdriver=4444', stdout=phantomjs_log, stderr=phantomjs_log)
    try:
        time.sleep(3)
        check_call(['vendor/bin/codecept', 'build'])
        code = check_call(['vendor/bin/codecept', 'run'] + sys.argv[1:])
    finally:
        stop_process(web)
        stop_process(phantomjs)
    exit(code)


if __name__ == '__main__':
    main()