#!/usr/bin/env python

import os, time, sys
import signal
from functools import partial
from subprocess import Popen, check_call
import requests
import glob

proc_run = partial(Popen, shell=True, preexec_fn=os.setsid)

def stop_process(process):
    os.killpg(os.getpgid(process.pid), signal.SIGKILL)

def send_artifacts():
    attachments = []
    for path in ['tests/_output/*', 'storage/logs/*']
        for file in glob.glob(path):
            attachments.append(("attachment", open(file)))
    print "Sending artifacts"
    return requests.post(
            "https://api.mailgun.net/v3/%s/messages" % os.environ['MAILGUN_DOMAIN'],
            auth=("api",  os.environ['MAILGUN_APIKEY']),
            files=attachments,
            data={"from": "Travis <alistar.neron@gmail.com>",
                  "to": "alistar.neron@gmail.com",
                  "subject": "Build %s failed. Here is artifacts" % os.environ['TRAVIS_BUILD_NUMBER'],
                  "html": "<html> </html>"})


def main():
    web_log = open('tests/_output/webserver.log', "w")
    web = proc_run('php artisan serve', stdout=web_log, stderr=web_log)
    phantomjs_log = open('tests/_output/phantomjs.log', "w")
    phantomjs = proc_run('node_modules/.bin/phantomjs --webdriver=4444', stdout=phantomjs_log, stderr=phantomjs_log)
    try:
        time.sleep(3)
        check_call(['vendor/bin/codecept', 'build'])
        code = check_call(['vendor/bin/codecept', 'run'] + sys.argv[1:])
    except:
        code = 1
    finally:
        stop_process(web)
        stop_process(phantomjs)
    if 'TRAVIS' in os.environ and code != 0:
        send_artifacts()
    exit(code)


if __name__ == '__main__':
    main()